FROM openjdk:8-jdk-alpine

FROM python3.11-slim

ENV DRUID_VERSION 0.23.0

ENV DRUID_HOME /opt/druid

RUN apk add --no-cache curl bash

RUN mkdir -p ${DRUID_HOME} && \
    curl -L https://dlcdn.apache.org/druid/${DRUID_VERSION}/apache-druid-${DRUID_VERSION}-bin.tar.gz | tar -xzf - -C ${DRUID_HOME} --strip-components=1

WORKDIR ${DRUID_HOME}

EXPOSE 8081 8082 8083 8090 8091 8888

CMD ["bash", "-c", "bin/start-druid"]
